### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by NikolaTesla13** [dreamos82/DreamOs#55]
I'm using Ubuntu WSL. 
I have an error with the file start.sh
Here is the cmd output:
```
C:\DreamOs>wsl sh start.sh grub
: not found0: start.sh:
: not found6: start.sh:
start.sh: 17: start.sh: Syntax error: word unexpected (expecting "in")

```
**Please solve the problem!**

**Comment by inuyasha82** [comment]
I'm tryin to guess, but the. script is written in bash, and you are trying to run it using sh, so sometime it can cause errors. 

Try that:

`chmod +x start.sh`

and then: 
`./start.sh grub`

Btw be careful while using that option, since it is going to overwrite your grub configuration, and if i remember correctly it support only a version of grub (the older one) so double check that this option is suitable for you. 

Btw you can use an emulator to run dreamos otherwise. 

Let me know if it solved your issue.

**Comment by NikolaTesla13** [comment]
I've already try it before post this issue. It didn't work...
Thanks for the grub advice!

**Comment by inuyasha82** [comment]
Ok, i need to do some tests first, but it will take couple of days since i need to reinstall all the development environment.

**Comment by Barrett17** [comment]
Actually you can just build an img and configure your own grub to run it.

Il Mar 21 Gen 2020, 23:57 Ivan <notifications@github.com> ha scritto:

**Comment by dreamos82** [comment]
Hi @NikolaTesla13  i'm trying to reproduce your issue, but for me is working both ways. Here a screenshot: 
![image](https://user-images.githubusercontent.com/59960116/73134840-4bf3cc80-4033-11ea-9df3-ad7a7142d0ff.png)

I see that you are using a windows os with linux subsystem, maybe this could be causing your problems. Please check that the linux subsystem is using bash, and if possible try to open the bash directly instead of launching it using wsl command (sorry i can't test on myself since i haven't used windows in last 10 years :D so i don't havae a suitable setup). Btw i think that even if it works you will face more challenges :D (we can use this issue to document the steps on how to run it on a win10 system with wsl). Btw i suggest you to test to compile it manually, and do the manual steps.
